generator: CPUtime.cpp uintx_t.h uintx_t.cpp Main.cpp Permutation.cpp Permutation.h PowerTable.cpp PowerTable.h Cayley.cpp Cayley.h mt19937-64.cpp Cayley32.h Cayley32.cpp
	g++ -O3 -std=c++11 -o generator.exe  CPUtime.cpp uintx_t.cpp Main.cpp Permutation.cpp PowerTable.cpp Cayley.cpp mt19937-64.cpp Cayley32.cpp
